services:
  contact-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: qodeq-contact-api
    restart: unless-stopped
    env_file:
      - ./server/.env
    expose:
      - "3001"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - contact-api
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/shared:/var/www/html
      - ./public:/var/www/html/qodeq_front:ro
      - ./nginx/certs/fullchain.pem:/tmp/ssl/fullchain.pem
      - ./nginx/certs/privkey.pem:/tmp/ssl/privkey.pem
